### ISSUE TITLE
[Feat] 최신 뉴스 자동 롤링

### ISSUE THREAD

**Issue by JeeeunOh** [JeeeunOh/fe-newsstand#1]
[Figma 링크](https://www.figma.com/proto/MKqcrGrNt2lOCiyYiMPNeu/FE_%EB%89%B4%EC%8A%A4%EC%8A%A4%ED%83%A0%EB%93%9C?page-id=11%3A2&type=design&node-id=68-25520&viewport=242%2C430%2C0.25&t=ZbpkrobPkl4KS15y-1&scaling=contain&starting-point-node-id=11%3A1923)

### 🚨 요구사항

1. 왼쪽 바와 오른쪽 바는 각각 다른 최신 뉴스 & 헤드라인 
2. 한 개의 바당 5개가 5초마다 무한 롤링
3. 좌우 영역의 롤링 시간차는 1초 → 동시 롤링 X
4. 롤링 시, 바 영역 안에서 제목이 위로 올라가는 애니메이션
5. 각 영역 호버 시 무한 롤링 일시정지
6. 각 영역 호버 시 헤드라인에 밑줄 표시

### 📌 해야할 일

- [x]  최신뉴스 & 헤드라인 10개 json 리스트업 ( `#1` )
- [x]  json 파일을 script.js로 가져오기
- [x]  각 영역 안에 5개의 헤드라인을 순서대로 위치시키기 ( `#2` )
- [x]  5초마다 보이는 헤드라인 요소를 하나씩 위로 이동시키기 ( `#2` )
    - [x]  왼쪽은 바로 이벤트 시작, 오른쪽은 1초 뒤에 이벤트 시작 ( `#3` )
- [x]  3번째 헤드라인을 현재 보여주고 있을 때, 가장 앞의 헤드라인을 삭제하고 가장 뒤에 붙이기 ( `#2` )
- [x]  css 이용해 5초마다 위로 올라가는 애니메이션 구현 ( `#4` )
- [x]  hover 시 롤링 일시정지 ( `#6` )
- [x]  hover 시 밑줄 표시 ( `#6` )
