### ISSUE TITLE
[Feat] 카테고리 프로그래스바 효과

### ISSUE THREAD

**Issue by JeeeunOh** [JeeeunOh/fe-newsstand#3]
[Figma 링크](https://www.figma.com/proto/MKqcrGrNt2lOCiyYiMPNeu/FE_%EB%89%B4%EC%8A%A4%EC%8A%A4%ED%83%A0%EB%93%9C?page-id=11%3A2&type=design&node-id=78-18284&viewport=242%2C430%2C0.25&t=ZbpkrobPkl4KS15y-1&scaling=contain&starting-point-node-id=11%3A1923)

### 🚨 요구사항

1. 프로그래스 바 구현
2. 카테고리 내 언론사 개수 & 순서 표시
3. 표시되는 언론사 순서 새로고침 시 랜덤
4. 20초(한 언론사 당 보여지는 시간)동안 프로그래스 바 차오름.
5. 20초 후에는 다음 언론사 내용 보여짐.

### 📌 해야할 일

- [x]  프로그래스 바 구현 ( `#1` )
    - [x]  카테고리 내 언론사 개수 & 순서 표시 ( `#2` )
- [x]  reload()시 언론사 순서 shuffle ( `#3` )
- [x]  20초동안 프로그래스바 차오르는 애니메이션 ( `#4` )
    - [x]  20초 후에는 다시 차오름. → 무한 차오름 ( `#4` )
    - [x]  20초 후에 다음 언론사 내용 보여짐 ( `#5` )
