### ISSUE TITLE
[Feat] 카테고리 간 이동

### ISSUE THREAD

**Issue by JeeeunOh** [JeeeunOh/fe-newsstand#4]
[Figma 링크](https://www.figma.com/proto/MKqcrGrNt2lOCiyYiMPNeu/FE_%EB%89%B4%EC%8A%A4%EC%8A%A4%ED%83%A0%EB%93%9C?page-id=11%3A2&type=design&node-id=78-20110&viewport=242%2C430%2C0.25&t=ZbpkrobPkl4KS15y-1&scaling=contain&starting-point-node-id=11%3A1923)

### 🚨 요구사항

1. 이전 카테고리 마지막 언론사 보여진 후 다음 카테고리로 넘어감.
2. 마지막 카테고리에서는, 첫 카테고리로 넘어감.
3. 좌우 화살표로 이전과 다음 언론사로 넘어가기 가능

### 📌 해야할 일

- [x]  이전 카테고리 마지막 언론사 보여진 후 다음 카테고리로 넘어감. ( `#1` )
- [x]  마지막 카테고리에서는 첫 카테고리로 넘어가게 ( `#2` )
- [x]  좌우 화살표 배치 ( `#3` )
- [x]  화살표 선택 시 카테고리 이동가능한 함수 구현 ( `#3` )
